from typing import Any, Dict, Optional

WORDING: Dict[str, Any] = {
    'conda_not_activated': 'Conda 环境未激活',
    'python_not_supported': '不支持当前 Python 版本，请升级到 {version} 或更高版本',
    'curl_not_installed': '未安装 CURL',
    'ffmpeg_not_installed': '未安装 FFmpeg',
    'creating_temp': '正在创建临时资源',
    'extracting_frames': '正在提取分辨率为 {resolution} 、帧率为 {fps} 的帧',
    'extracting_frames_succeed': '帧提取成功',
    'extracting_frames_failed': '帧提取失败',
    'analysing': '正在分析',
    'extracting': '正在提取',
    'streaming': '正在流式处理',
    'processing': '正在处理',
    'merging': '正在合并',
    'downloading': '正在下载',
    'temp_frames_not_found': '未找到临时帧',
    'copying_image': '正在复制分辨率为 {resolution} 的图像',
    'copying_image_succeed': '图像复制成功',
    'copying_image_failed': '图像复制失败',
    'finalizing_image': '正在完成分辨率为 {resolution} 的图像',
    'finalizing_image_succeed': '图像处理完成',
    'finalizing_image_skipped': '图像处理跳过',
    'merging_video': '正在合并分辨率为 {resolution} 、帧率为 {fps} 的视频',
    'merging_video_succeed': '视频合并成功',
    'merging_video_failed': '视频合并失败',
    'skipping_audio': '正在跳过音频处理',
    'replacing_audio_succeed': '音频替换成功',
    'replacing_audio_skipped': '音频替换跳过',
    'restoring_audio_succeed': '音频恢复成功',
    'restoring_audio_skipped': '音频恢复跳过',
    'clearing_temp': '正在清理临时资源',
    'processing_stopped': '处理已停止',
    'processing_image_succeed': '图像处理成功，耗时 {seconds} 秒',
    'processing_image_failed': '图像处理失败',
    'processing_video_succeed': '视频处理成功，耗时 {seconds} 秒',
    'processing_video_failed': '视频处理失败',
    'choose_image_source': '选择源人脸图像',
    'choose_audio_source': '选择源音频',
    'choose_video_target': '选择目标视频',
    'choose_image_or_video_target': '选择目标图像或视频',
    'specify_image_or_video_output': '指定输出图像或视频的保存目录',
    'match_target_and_output_extension': '目标文件与输出文件的扩展名需匹配',
    'no_source_face_detected': '未检测到源人脸',
    'processor_not_loaded': '无法加载处理器 {processor}',
    'processor_not_implemented': '处理器 {processor} 实现不正确',
    'ui_layout_not_loaded': '无法加载 UI 布局 {ui_layout}',
    'ui_layout_not_implemented': 'UI 布局 {ui_layout} 实现不正确',
    'stream_not_loaded': '无法加载流 {stream_mode}',
    'stream_not_supported': '不支持当前流模式',
    'job_created': '已创建任务 {job_id}',
    'job_not_created': '任务 {job_id} 创建失败',
    'job_submitted': '已提交任务 {job_id}',
    'job_not_submitted': '任务 {job_id} 提交失败',
    'job_all_submitted': '所有任务已提交',
    'job_all_not_submitted': '所有任务提交失败',
    'job_deleted': '已删除任务 {job_id}',
    'job_not_deleted': '任务 {job_id} 删除失败',
    'job_all_deleted': '所有任务已删除',
    'job_all_not_deleted': '所有任务删除失败',
    'job_step_added': '已向任务 {job_id} 添加步骤',
    'job_step_not_added': '向任务 {job_id} 添加步骤失败',
    'job_remix_step_added': '已从任务 {job_id}  remix 步骤 {step_index}',
    'job_remix_step_not_added': '从任务 {job_id} remix 步骤 {step_index} 失败',
    'job_step_inserted': '已向任务 {job_id} 插入步骤 {step_index}',
    'job_step_not_inserted': '向任务 {job_id} 插入步骤 {step_index} 失败',
    'job_step_removed': '已从任务 {job_id} 移除步骤 {step_index}',
    'job_step_not_removed': '从任务 {job_id} 移除步骤 {step_index} 失败',
    'running_job': '正在运行排队任务 {job_id}',
    'running_jobs': '正在运行所有排队任务',
    'retrying_job': '正在重试失败任务 {job_id}',
    'retrying_jobs': '正在重试所有失败任务',
    'processing_job_succeed': '任务 {job_id} 处理成功',
    'processing_jobs_succeed': '所有任务处理成功',
    'processing_job_failed': '任务 {job_id} 处理失败',
    'processing_jobs_failed': '所有任务处理失败',
    'processing_step': '正在处理第 {step_current} 步，共 {step_total} 步',
    'validating_hash_succeed': '验证 {hash_file_name} 的哈希值成功',
    'validating_hash_failed': '验证 {hash_file_name} 的哈希值失败',
    'validating_source_succeed': '验证 {source_file_name} 源文件成功',
    'validating_source_failed': '验证 {source_file_name} 源文件失败',
    'deleting_corrupt_source': '正在删除损坏的 {source_file_name} 源文件',
    'time_ago_now': '刚刚',
    'time_ago_minutes': '{minutes} 分钟前',
    'time_ago_hours': '{hours} 小时 {minutes} 分钟前',
    'time_ago_days': '{days} 天 {hours} 小时 {minutes} 分钟前',
    'point': '。',
    'comma': '，',
    'colon': '：',
    'question_mark': '？',
    'exclamation_mark': '！',
    'help': {
        # installer
        'install_dependency': '选择要安装的 {dependency} 版本',
        'skip_conda': '跳过 conda 环境检查',
        # paths
        'config_path': '选择配置文件以覆盖默认设置',
        'temp_path': '指定临时资源的存储目录',
        'jobs_path': '指定任务存储目录',
        'source_paths': '选择源图像或音频路径',
        'target_path': '选择目标图像或视频路径',
        'output_path': '指定图像或视频的输出目录',
        # patterns
        'source_pattern': '选择源图像或音频的匹配模式',
        'target_pattern': '选择目标图像或视频的匹配模式',
        'output_pattern': '指定图像或视频的输出模式',
        # face detector
        'face_detector_model': '选择用于检测人脸的模型',
        'face_detector_size': '指定提供给人脸检测器的帧大小',
        'face_detector_angles': '指定检测人脸前旋转帧的角度',
        'face_detector_score': '基于置信度分数过滤检测到的人脸',
        # face landmarker
        'face_landmarker_model': '选择用于检测人脸 landmarks 的模型',
        'face_landmarker_score': '基于置信度分数过滤检测到的人脸 landmarks',
        # face selector
        'face_selector_mode': '使用基于参考的跟踪或简单匹配',
        'face_selector_order': '指定检测到的人脸顺序',
        'face_selector_age_start': '基于起始年龄过滤检测到的人脸',
        'face_selector_age_end': '基于结束年龄过滤检测到的人脸',
        'face_selector_gender': '基于性别过滤检测到的人脸',
        'face_selector_race': '基于种族过滤检测到的人脸',
        'reference_face_position': '指定用于创建参考人脸的位置',
        'reference_face_distance': '指定参考人脸与目标人脸的相似度',
        'reference_frame_number': '指定用于创建参考人脸的帧',
        # face masker
        'face_occluder_model': '选择用于遮挡掩码的模型',
        'face_parser_model': '选择用于区域掩码的模型',
        'face_mask_types': '混合搭配不同的人脸掩码类型（选项：{choices}）',
        'face_mask_blur': '指定应用于框掩码的模糊程度',
        'face_mask_padding': '对框掩码应用上、右、下、左填充',
        'face_mask_regions': '选择用于区域掩码的面部特征（选项：{choices}）',
        # frame extraction
        'trim_frame_start': '指定目标视频的起始帧',
        'trim_frame_end': '指定目标视频的结束帧',
        'temp_frame_format': '指定临时资源的格式',
        'keep_temp': '处理后保留临时资源',
        # output creation
        'output_image_quality': '指定图像质量，对应图像压缩率',
        'output_image_resolution': '基于目标图像指定输出图像分辨率',
        'output_audio_encoder': '指定用于音频的编码器',
        'output_audio_quality': '指定音频质量，对应音频压缩率',
        'output_audio_volume': '基于目标视频指定音频音量',
        'output_video_encoder': '指定用于视频的编码器',
        'output_video_preset': '平衡快速视频处理和视频文件大小',
        'output_video_quality': '指定视频质量，对应视频压缩率',
        'output_video_resolution': '基于目标视频指定输出视频分辨率',
        'output_video_fps': '基于目标视频指定视频帧率',
        # processors
        'processors': '加载单个或多个处理器（选项：{choices} 等）',
        'age_modifier_model': '选择用于面部年龄修改的模型',
        'age_modifier_direction': '指定年龄修改的方向',
        'deep_swapper_model': '选择用于人脸交换的模型',
        'deep_swapper_morph': '在源人脸和目标人脸之间变形',
        'expression_restorer_model': '选择用于表情恢复的模型',
        'expression_restorer_factor': '从目标人脸恢复表情的因子',
        'face_debugger_items': '加载单个或多个处理器（选项：{choices}）',
        'face_editor_model': '选择用于面部编辑的模型',
        'face_editor_eyebrow_direction': '指定眉毛方向',
        'face_editor_eye_gaze_horizontal': '指定水平眼 gaze',
        'face_editor_eye_gaze_vertical': '指定垂直眼 gaze',
        'face_editor_eye_open_ratio': '指定眼睛睁开比例',
        'face_editor_lip_open_ratio': '指定嘴唇张开比例',
        'face_editor_mouth_grim': '指定嘴部 grim',
        'face_editor_mouth_pout': '指定嘴部 pout',
        'face_editor_mouth_purse': '指定嘴部 purse',
        'face_editor_mouth_smile': '指定嘴部微笑程度',
        'face_editor_mouth_position_horizontal': '指定嘴部水平位置',
        'face_editor_mouth_position_vertical': '指定嘴部垂直位置',
        'face_editor_head_pitch': '指定头部俯仰角度',
        'face_editor_head_yaw': '指定头部偏航角度',
        'face_editor_head_roll': '指定头部翻滚角度',
        'face_enhancer_model': '选择用于面部增强的模型',
        'face_enhancer_blend': '将增强效果混合到前一张人脸',
        'face_enhancer_weight': '指定应用于面部的权重程度',
        'face_swapper_model': '选择用于人脸交换的模型',
        'face_swapper_pixel_boost': '选择人脸交换器的像素提升分辨率',
        'frame_colorizer_model': '选择用于帧着色的模型',
        'frame_colorizer_size': '指定提供给帧着色器的帧大小',
        'frame_colorizer_blend': '将着色效果混合到前一帧',
        'frame_enhancer_model': '选择用于帧增强的模型',
        'frame_enhancer_blend': '将增强效果混合到前一帧',
        'lip_syncer_model': '选择用于嘴唇同步的模型',
        # uis
        'open_browser': '程序准备就绪后打开浏览器',
        'ui_layouts': '启动单个或多个 UI 布局（选项：{choices} 等）',
        'ui_workflow': '选择 UI 工作流程',
        # execution
        'execution_device_id': '指定用于处理的设备',
        'execution_providers': '使用不同的提供程序进行推理（选项：{choices} 等）',
        'execution_thread_count': '指定处理时的并行线程数量',
        'execution_queue_count': '指定每个线程处理的帧数',
        # download
        'download_providers': '使用不同的提供程序下载（选项：{choices} 等）',
        'download_scope': '指定下载范围',
        # memory
        'video_memory_strategy': '平衡快速处理和低 VRAM 使用',
        'system_memory_limit': '限制处理时可用的 RAM 容量',
        # misc
        'log_level': '调整终端中显示的消息严重程度',
        'halt_on_error': '发生错误时停止程序',
        # run
        'run': '运行程序',
        'headless_run': '以无头模式运行程序',
        'batch_run': '以批处理模式运行程序',
        'force_download': '强制自动下载并退出',
        # jobs
        'job_id': '指定任务 ID',
        'job_status': '指定任务状态',
        'step_index': '指定步骤索引',
        # job manager
        'job_list': '按状态列出任务',
        'job_create': '创建一个草拟任务',
        'job_submit': '提交草拟任务以成为排队任务',
        'job_submit_all': '提交所有草拟任务以成为排队任务',
        'job_delete': '删除草拟、排队、失败或已完成的任务',
        'job_delete_all': '删除所有草拟、排队、失败和已完成的任务',
        'job_add_step': '向草拟任务添加步骤',
        'job_remix_step': '从草拟任务 remix 先前步骤',
        'job_insert_step': '向草拟任务插入步骤',
        'job_remove_step': '从草拟任务移除步骤',
        # job runner
        'job_run': '运行排队任务',
        'job_run_all': '运行所有排队任务',
        'job_retry': '重试失败任务',
        'job_retry_all': '重试所有失败任务'
    },
    'about': {
        'become_a_member': '成为会员',
        'join_our_community': '加入我们的社区',
        'read_the_documentation': '阅读文档'
    },
    'uis': {
        'age_modifier_direction_slider': '年龄修改方向',
        'age_modifier_model_dropdown': '年龄修改模型',
        'apply_button': '应用',
        'benchmark_cycles_slider': '基准测试周期数',
        'benchmark_runs_checkbox_group': '基准测试运行项',
        'clear_button': '清除',
        'common_options_checkbox_group': '选项',
        'download_providers_checkbox_group': '下载提供程序',
        'deep_swapper_model_dropdown': '深度交换模型',
        'deep_swapper_morph_slider': '深度交换变形',
        'execution_providers_checkbox_group': '执行提供程序',
        'execution_queue_count_slider': '执行队列数量',
        'execution_thread_count_slider': '执行线程数量',
        'expression_restorer_factor_slider': '表情恢复因子',
        'expression_restorer_model_dropdown': '表情恢复模型',
        'face_debugger_items_checkbox_group': '人脸调试项',
        'face_detector_angles_checkbox_group': '人脸检测器角度',
        'face_detector_model_dropdown': '人脸检测器模型',
        'face_detector_score_slider': '人脸检测器分数',
        'face_detector_size_dropdown': '人脸检测器尺寸',
        'face_editor_eyebrow_direction_slider': '人脸编辑眉毛方向',
        'face_editor_eye_gaze_horizontal_slider': '人脸编辑眼睛水平凝视',
        'face_editor_eye_gaze_vertical_slider': '人脸编辑眼睛垂直凝视',
        'face_editor_eye_open_ratio_slider': '人脸编辑眼睛睁开比例',
        'face_editor_head_pitch_slider': '人脸编辑头部俯仰',
        'face_editor_head_roll_slider': '人脸编辑头部翻滚',
        'face_editor_head_yaw_slider': '人脸编辑头部偏航',
        'face_editor_lip_open_ratio_slider': '人脸编辑嘴唇张开比例',
        'face_editor_model_dropdown': '人脸编辑模型',
        'face_editor_mouth_grim_slider': '人脸编辑嘴部 grim',
        'face_editor_mouth_position_horizontal_slider': '人脸编辑嘴部水平位置',
        'face_editor_mouth_position_vertical_slider': '人脸编辑嘴部垂直位置',
        'face_editor_mouth_pout_slider': '人脸编辑嘴部 pout',
        'face_editor_mouth_purse_slider': '人脸编辑嘴部 purse',
        'face_editor_mouth_smile_slider': '人脸编辑嘴部微笑',
        'face_enhancer_blend_slider': '人脸增强混合',
        'face_enhancer_model_dropdown': '人脸增强模型',
        'face_enhancer_weight_slider': '人脸增强权重',
        'face_landmarker_model_dropdown': '人脸 landmark 模型',
        'face_landmarker_score_slider': '人脸 landmark 分数',
        'face_mask_blur_slider': '人脸掩码模糊',
        'face_mask_padding_bottom_slider': '人脸掩码底部填充',
        'face_mask_padding_left_slider': '人脸掩码左侧填充',
        'face_mask_padding_right_slider': '人脸掩码右侧填充',
        'face_mask_padding_top_slider': '人脸掩码顶部填充',
        'face_mask_regions_checkbox_group': '人脸掩码区域',
        'face_mask_types_checkbox_group': '人脸掩码类型',
        'face_selector_age_range_slider': '人脸选择年龄范围',
        'face_selector_gender_dropdown': '人脸选择性别',
        'face_selector_mode_dropdown': '人脸选择模式',
        'face_selector_order_dropdown': '人脸选择顺序',
        'face_selector_race_dropdown': '人脸选择种族',
        'face_swapper_model_dropdown': '人脸交换模型',
        'face_swapper_pixel_boost_dropdown': '人脸交换像素提升',
        'face_occluder_model_dropdown': '人脸遮挡模型',
        'face_parser_model_dropdown': '人脸解析模型',
        'frame_colorizer_blend_slider': '帧着色混合',
        'frame_colorizer_model_dropdown': '帧着色模型',
        'frame_colorizer_size_dropdown': '帧着色尺寸',
        'frame_enhancer_blend_slider': '帧增强混合',
        'frame_enhancer_model_dropdown': '帧增强模型',
        'job_list_status_checkbox_group': '任务列表状态',
        'job_manager_job_action_dropdown': '任务管理器操作',
        'job_manager_job_id_dropdown': '任务 ID',
        'job_manager_step_index_dropdown': '步骤索引',
        'job_runner_job_action_dropdown': '任务运行器操作',
        'job_runner_job_id_dropdown': '任务 ID',
        'lip_syncer_model_dropdown': '嘴唇同步模型',
        'log_level_dropdown': '日志级别',
        'output_audio_encoder_dropdown': '输出音频编码器',
        'output_audio_quality_slider': '输出音频质量',
        'output_audio_volume_slider': '输出音频音量',
        'output_image_or_video': '输出',
        'output_image_quality_slider': '输出图像质量',
        'output_image_resolution_dropdown': '输出图像分辨率',
        'output_path_textbox': '输出路径',
        'output_video_encoder_dropdown': '输出视频编码器',
        'output_video_fps_slider': '输出视频帧率',
        'output_video_preset_dropdown': '输出视频预设',
        'output_video_quality_slider': '输出视频质量',
        'output_video_resolution_dropdown': '输出视频分辨率',
        'preview_frame_slider': '预览帧',
        'preview_image': '预览',
        'processors_checkbox_group': '处理器',
        'reference_face_distance_slider': '参考人脸距离',
        'reference_face_gallery': '参考人脸库',
        'refresh_button': '刷新',
        'source_file': '源文件',
        'start_button': '开始',
        'stop_button': '停止',
        'system_memory_limit_slider': '系统内存限制',
        'target_file': '目标文件',
        'temp_frame_format_dropdown': '临时帧格式',
        'terminal_textbox': '终端',
        'trim_frame_slider': '修剪帧',
        'ui_workflow': 'UI 工作流程',
        'video_memory_strategy_dropdown': '视频内存策略',
        'webcam_fps_slider': '网络摄像头帧率',
        'webcam_image': '网络摄像头',
        'webcam_device_id_dropdown': '网络摄像头设备 ID',
        'webcam_mode_radio': '网络摄像头模式',
        'webcam_resolution_dropdown': '网络摄像头分辨率'
    }
}


def get(notation: str) -> Optional[str]:
    current = WORDING

    for fragment in notation.split('.'):
        if fragment in current:
            current = current.get(fragment)
            if isinstance(current, str):
                return current

    return None
